apiVersion: apps/v1
kind: Deployment
metadata:
  name: pyapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pyapp
  template:
    metadata:
      labels:
        app: pyapp
    spec:
      containers:
      - name: pyapp
        image: anilyadav53/pyapp:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: pyapp-service
spec:
  selector:
    app: pyapp
  ports:
    - protocol: TCP
      port: 5000       # Change from 80 to 5000
      targetPort: 5000
      nodePort: 30486  # Optional, choose a fixed NodePort
  type: NodePort

