apiVersion: v1
kind: Service
metadata:
  name: pyapp-service
spec:
  selector:
    app: pyapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9090
  type: LoadBalancer  # Exposes the service externally
